# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev", "elmarie/*" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build_Test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up Python 3.11.7
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.7

      # Set up a virtual environment and activate it
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Install Python libraries
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Check linting and formatting
      - name: Check linting and formatting
        run: |
          black ./ --check
          pylint src/*.py src/tests/*.py

      # Run tests and make coverage report
      # TODO: Test paths not resolving properly (need to investigate)
      # - name: Run tests
      #   run: |
      #     pytest --cov-report term-missing --cov=. --cov-fail-under=0 ./